#!/usr/bin/env bash
# Host tests for Galleria 2007 (no ESP-IDF needed).
#
#   tests/run_tests.sh          unit tests + gameplay tests (IT and EN)
#   tests/run_tests.sh shots    also render screenshots to build/shots/*.png
#
# PRG32_REPO points to the PRG32 checkout (default ../PRG32); its public
# headers and firmware font are used so host behaviour matches the cartridge.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
prg32="$(cd "${PRG32_REPO:-$root/../PRG32}" && pwd)"
out="$root/build/tests"
mkdir -p "$out"
cflags=(-std=c99 -Wall -Wextra -Werror -O1 -g -fsanitize=address,undefined
        -I "$root/src" -I "$root/tests/host"
        -I "$prg32/components/prg32/include" -I "$prg32/components/prg32_audio/include")

# The 8x8 font comes from the firmware so host text matches the device.
python3 - "$prg32" "$root/tests/host/font8.h" <<'PY'
import re, sys
src = open(sys.argv[1] + "/components/prg32/prg32_display_qemu_rgb.c").read()
font = re.search(r"static const uint8_t g_font8\[96\]\[8\].*?\n};", src, re.S).group(0)
font = font.replace(" PRG32_FLASH_RODATA", "")
open(sys.argv[2], "w").write("/* Generated by tests/run_tests.sh from the PRG32 firmware font. */\n" + font + "\n")
PY

langs=()
for f in "$root"/lang/*.json; do langs+=("$(basename "$f" .json | tr '[:lower:]' '[:upper:]')"); done

fail=0
for t in test_fixed test_world test_inventory test_ai test_protocol test_input; do
  cc "${cflags[@]}" "$root/tests/$t.c" -o "$out/$t"
  "$out/$t" || fail=1
done
for lang in "${langs[@]}"; do
  cc "${cflags[@]}" -DG2007_LANG_$lang "$root/tests/test_game.c" -o "$out/test_game_$lang" -lm
  "$out/test_game_$lang" || fail=1
done
if [[ "${1:-}" == "shots" ]]; then
  for lang in "${langs[@]}"; do
    shots="$root/build/shots/$(echo $lang | tr A-Z a-z)"
    mkdir -p "$shots"
    cc "${cflags[@]}" -DG2007_LANG_$lang "$root/tests/host/shots.c" -o "$out/shots_$lang"
    "$out/shots_$lang" "$shots"
    python3 - "$shots" <<'PY'
import sys
from pathlib import Path
from PIL import Image
for ppm in sorted(Path(sys.argv[1]).glob("*.ppm")):
    Image.open(ppm).save(ppm.with_suffix(".png"))
    ppm.unlink()
PY
  done
fi
exit $fail
