#!/usr/bin/env bash
# Build Galleria 2007 cartridges: every language variant for every target.
#
#   scripts/build.sh                 # it+en, esp32c6+qemu
#   LANGS="it" scripts/build.sh qemu # one language, one architecture
#
# Environment:
#   PRG32_REPO   path to the PRG32 repository (default ../PRG32)
#   IDF_EXPORT   ESP-IDF export script, sourced when riscv32-esp-elf-gcc is not
#                on PATH (default $HOME/esp-idf/export.sh)
#   LANGS        language codes to build (default: every lang/*.json)
#
# Outputs dist/galleria2007-<lang>-<arch>.prg32 (Store-ready: metadata, icon,
# screenshot and colophon attached) and prints the three PRG32 budgets.
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
prg32_repo="$(cd "${PRG32_REPO:-"$repo_dir/../PRG32"}" && pwd)"
cart_ram_kib=64          # PRG32 default "extended" profile (ESP32-C6 and QEMU)
package_limit=65536      # stored package limit (code + audio + metadata)
load_limit=54500         # measured QEMU limit for header + code/data + audio

if ! command -v riscv32-esp-elf-gcc >/dev/null 2>&1; then
  idf_export="${IDF_EXPORT:-$HOME/esp-idf/export.sh}"
  # shellcheck disable=SC1090
  [[ -f "$idf_export" ]] && source "$idf_export" >/dev/null 2>&1
fi
command -v riscv32-esp-elf-gcc >/dev/null 2>&1 || {
  echo "error: riscv32-esp-elf-gcc not found; source ESP-IDF export.sh first" >&2
  exit 2
}

archs=("$@")
[[ ${#archs[@]} -eq 0 ]] && archs=(esp32c6 qemu)
if [[ -n "${LANGS:-}" ]]; then
  read -r -a langs <<< "$LANGS"
else
  langs=()
  for f in "$repo_dir"/lang/*.json; do langs+=("$(basename "$f" .json)"); done
fi

build_dir="$repo_dir/build"
dist_dir="$repo_dir/dist"
mkdir -p "$build_dir" "$dist_dir"

# Older PRG32 checkouts lack --cart-ram-kib; tools/prg32_cli.py then raises
# only the host-side RAM check to the firmware's 64 KiB default.
prg32() {
  (cd "$prg32_repo" && PRG32_REPO="$prg32_repo" python3 "$repo_dir/tools/prg32_cli.py" "$@")
}

# 1. Regenerate every derived source (deterministic; results are committed).
python3 "$repo_dir/tools/build_ids.py" >/dev/null
python3 "$repo_dir/tools/build_map.py"
python3 "$repo_dir/tools/build_assets.py"
python3 "$repo_dir/tools/build_strings.py"
python3 "$repo_dir/tools/build_audio.py"
python3 "$repo_dir/tools/validate_assets.py"

# 2. AUDIO block (procedural instruments only, no PCM).
python3 "$prg32_repo/tools/prg32audio_pack.py" "$repo_dir/audio/audio.json" \
  --out "$build_dir/audio.block"

for lang in "${langs[@]}"; do
  LANG_UP="$(echo "$lang" | tr '[:lower:]' '[:upper:]')"
  for arch in "${archs[@]}"; do
    name="galleria2007-$lang"
    raw="$build_dir/$name-$arch.raw.prg32"
    out="$dist_dir/$name-$arch.prg32"
    # 3. A tiny wrapper selects the language: the builder takes one source.
    wrapper="$build_dir/galleria2007_${lang}_${arch}.c"
    {
      echo "/* Generated by scripts/build.sh: $lang cartridge for $arch. */"
      echo "#define G2007_LANG_$LANG_UP 1"
      echo "#include \"$repo_dir/src/galleria2007.c\""
    } > "$wrapper"
    log="$build_dir/$name-$arch.build.log"
    prg32 cartridge build "$wrapper" \
      --portable --multiplayer \
      --entry-prefix galleria2007 \
      --name "$name" \
      --architecture "$arch" \
      --cart-ram-kib "$cart_ram_kib" \
      --audio-block "$build_dir/audio.block" \
      --out "$raw" | tee "$log"
    sizes="$(grep -o 'code=[0-9]* mem=[0-9]* audio=[0-9]*' "$log" | tail -1)"
    code="$(sed -E 's/code=([0-9]+).*/\1/' <<< "$sizes")"
    mem="$(sed -E 's/.*mem=([0-9]+).*/\1/' <<< "$sizes")"
    audio="$(sed -E 's/.*audio=([0-9]+)/\1/' <<< "$sizes")"
    load=$(( code + audio + 128 ))

    # 4. Store trailer: metadata, icon, screenshot and colophon per language.
    prg32 store attach-metadata "$raw" --out "$out" \
      --metadata "$repo_dir/metadata/metadata.$lang.json" \
      --icon "$repo_dir/assets/store/icon.png" \
      --screenshot "$repo_dir/assets/store/screenshot-$lang.png" \
      --colophon "$repo_dir/metadata/colophon.$lang.json" \
      --architecture "$arch" >/dev/null

    size=$(wc -c < "$out" | tr -d ' ')
    echo "$out: package $size/$package_limit, RAM $mem/$(( cart_ram_kib * 1024 )), load ~$load/$load_limit"
    (( size <= package_limit )) || { echo "error: package too large" >&2; exit 1; }
    (( mem <= cart_ram_kib * 1024 )) || { echo "error: executable RAM exceeded" >&2; exit 1; }
    (( load <= load_limit )) || { echo "error: load image too large for QEMU" >&2; exit 1; }
  done
done

# 5. Inspect what was produced.
for f in "$dist_dir"/galleria2007-*.prg32; do
  prg32 cartridge summary "$f" | tail -n +1 > "$build_dir/$(basename "$f").summary.txt"
  prg32 store inspect-metadata "$f" > "$build_dir/$(basename "$f").metadata.txt"
done
(cd "$dist_dir" && shasum -a 256 galleria2007-*.prg32 > SHA256SUMS)
echo "summaries in $build_dir/*.summary.txt; checksums in dist/SHA256SUMS"
