#!/usr/bin/env python3
"""Generate src/gen/ids.h from tools/g2007_ids.py (deterministic)."""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import g2007_ids as ids  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]


def enum(prefix, names):
    lines = []
    for i, n in enumerate(names):
        name = n[0] if isinstance(n, tuple) else n
        lines.append(f"#define {prefix}{name} {i}")
    lines.append(f"#define {prefix}COUNT {len(names)}")
    return lines


def main():
    out = ["/* Generated by tools/build_ids.py from tools/g2007_ids.py. Do not edit. */",
           "#ifndef G2007_GEN_IDS_H", "#define G2007_GEN_IDS_H", ""]
    out += enum("TEX_", ids.TEXTURES) + [""]
    out += enum("PAT_", ids.PATTERNS) + [""]
    out += enum("MAT_", ids.MATERIALS) + [""]
    out += enum("ITEM_", ids.ITEMS) + [""]
    out += enum("ENT_", ids.ENTITY_KINDS) + [""]
    out += enum("DOOR_", ids.DOORS) + [""]
    out += enum("ZONE_", ids.ZONES) + [""]
    out += [f"#define SECF_{n} (1u << {i})" for i, n in enumerate(ids.SECTOR_FLAGS)] + [""]
    out += enum("ARC_", ids.ARCHIVE) + [""]
    out += enum("PROV_", ids.PROVENANCE) + [""]
    out += enum("SPR_", ids.SPRITES) + [""]
    mask = 0
    for n in ids.CRITICAL_ITEMS:
        mask |= 1 << ids.ITEMS.index(n)
    out += [f"#define ITEM_CRITICAL_MASK 0x{mask:04x}u", "", "#endif", ""]
    path = ROOT / "src/gen/ids.h"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
