#!/usr/bin/env python3
"""Embed the PRG32 firmware 8x8 font (ASCII 32..126) in the cartridge.

PRG32-QT and PRG32-iOS draw prg32_gfx_text8() with a reduced 5x7 font
(A-Z, 0-9 and a few signs), so apostrophes, brackets and '>' would become
'?'. The cartridge therefore composes its own text into the render strips
with the firmware's font, giving identical text on every host. The font is
part of PRG32 (MIT, (c) PRG32 contributors); see assets/source/SOURCES.md.

Reads $PRG32_REPO/components/prg32/prg32_display_qemu_rgb.c (default
../PRG32) and writes src/gen/font8.h (committed, so builds do not need it).
"""
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRG32 = Path(os.environ.get("PRG32_REPO", ROOT.parent / "PRG32"))


def main():
    src = (PRG32 / "components/prg32/prg32_display_qemu_rgb.c").read_text(encoding="utf-8")
    body = re.search(r"static const uint8_t g_font8\[96\]\[8\][^=]*=\s*\{(.*?)\n\};", src, re.S).group(1)
    # Entries are designated initialisers: ['A' - 32] = {0x.., ...}.
    glyphs = {}
    for m in re.finditer(r"\[\s*'(\\.|[^'])'\s*-\s*32\s*\]\s*=\s*\{([^}]*)\}", body):
        ch = m.group(1)[-1] if m.group(1).startswith("\\") else m.group(1)
        glyphs[ord(ch)] = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]+)", m.group(2))]
    missing = [chr(c) for c in range(32, 127) if c not in glyphs or len(glyphs[c]) != 8]
    if missing:
        raise SystemExit(f"font glyphs missing: {missing}")
    values = [v for c in range(32, 127) for v in glyphs[c]]
    out = ["/* Generated by tools/build_font.py from the PRG32 firmware font (MIT).",
           " * ASCII 32..126, 8x8, most significant bit = leftmost pixel. */",
           "#ifndef G2007_GEN_FONT8_H", "#define G2007_GEN_FONT8_H", "",
           "static const uint8_t g_ui_font[95][8] = {"]
    for c in range(95):
        row = values[c * 8:(c + 1) * 8]
        ch = chr(32 + c)
        label = {"\\": "backslash", "*": "star"}.get(ch, ch)
        out.append("    {" + ", ".join(f"0x{v:02x}" for v in row) + f"}}, /* {label} */")
    out += ["};", "", "#endif", ""]
    (ROOT / "src/gen/font8.h").write_text("\n".join(out), encoding="utf-8")
    print("font: 95 glyphs, 760 bytes")


if __name__ == "__main__":
    main()
