#!/usr/bin/env python3
"""Compile language files (lang/*.json) into C string tables.

Every language produces one ``src/gen/strings_<code>.h``; all languages
share ``src/gen/string_ids.h``, whose ids follow the key order of the primary
language (``lang/it.json``). A cartridge is built for exactly one language,
so only that language's text costs executable RAM.

Strings are stored as one concatenated ``char`` array plus a ``uint16_t``
offset table. This keeps the data position-independent: PRG32 portable
cartridges must not contain pointer tables, which would need relocation.

Validation (errors abort the build):
  * every language has exactly the primary language's keys;
  * after transliteration every character is printable ASCII (PRG32 8x8 font);
  * every line fits the 38-column text area; archive bodies have 2..5 lines.
Accented letters are transliterated in the traditional all-caps Italian way
(``È`` -> ``E'``) because the PRG32 font has no accented glyphs.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRIMARY = "it"
MAX_COLS = 38
TRANSLIT = {"À": "A'", "È": "E'", "É": "E'", "Ì": "I'", "Ò": "O'", "Ù": "U'",
            "à": "a'", "è": "e'", "é": "e'", "ì": "i'", "ò": "o'", "ù": "u'",
            "’": "'", "–": "-", "—": "-"}


def load(code: str) -> dict:
    data = json.loads((ROOT / "lang" / f"{code}.json").read_text(encoding="utf-8"))
    data.pop("_meta", None)
    return data


def translit(text: str) -> str:
    return "".join(TRANSLIT.get(ch, ch) for ch in text)


def validate(code: str, key: str, text: str) -> list[str]:
    errors = []
    for ch in text:
        if ch != "\n" and not 32 <= ord(ch) <= 126:
            errors.append(f"{code}:{key}: unsupported character {ch!r}")
    lines = text.split("\n")
    for line in lines:
        if len(line) > MAX_COLS:
            errors.append(f"{code}:{key}: line longer than {MAX_COLS}: {line!r}")
    if key.startswith("A") and key.endswith("_BODY") and not 2 <= len(lines) <= 5:
        errors.append(f"{code}:{key}: archive bodies need 2..5 lines")
    if len(lines) > 9:
        errors.append(f"{code}:{key}: more than 9 lines")
    return errors


def c_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '\\0"'


def languages() -> list[str]:
    return sorted(p.stem for p in (ROOT / "lang").glob("*.json"))


def main() -> int:
    primary = load(PRIMARY)
    keys = list(primary.keys())
    if len(keys) > 255:
        raise SystemExit("too many strings for uint8 entity name fields")
    errors = []
    out_ids = ["/* Generated by tools/build_strings.py. Do not edit. */",
               "#ifndef G2007_GEN_STRING_IDS_H", "#define G2007_GEN_STRING_IDS_H", ""]
    out_ids += [f"#define S_{k} {i}" for i, k in enumerate(keys)]
    out_ids += [f"#define S_COUNT {len(keys)}", "", "#endif", ""]
    (ROOT / "src/gen").mkdir(parents=True, exist_ok=True)
    (ROOT / "src/gen/string_ids.h").write_text("\n".join(out_ids), encoding="utf-8")
    sizes = {}
    for code in languages():
        data = load(code)
        missing = [k for k in keys if k not in data]
        extra = [k for k in data if k not in primary]
        if missing or extra:
            errors.append(f"{code}: missing keys {missing}, unexpected keys {extra}")
            continue
        texts = [translit(data[k]) for k in keys]
        for k, t in zip(keys, texts):
            errors += validate(code, k, t)
        offsets, pos = [], 0
        for t in texts:
            offsets.append(pos)
            pos += len(t.encode("ascii", "replace")) + 1
        if pos > 65535:
            errors.append(f"{code}: text table exceeds 64 KiB")
        guard = f"G2007_GEN_STRINGS_{code.upper()}_H"
        out = [f"/* Generated by tools/build_strings.py from lang/{code}.json. Do not edit. */",
               f"#ifndef {guard}", f"#define {guard}", "",
               f'#define G2007_LANG_CODE "{code.upper()}"', "",
               "static const char g_text[] ="]
        out += [f"    {c_string(t)} /* {k} */" for k, t in zip(keys, texts)]
        out[-1] += ";"
        out += ["", "static const uint16_t g_text_off[S_COUNT] = {"]
        for i in range(0, len(offsets), 12):
            out.append("    " + ", ".join(str(o) for o in offsets[i:i + 12]) + ",")
        out += ["};", "", "#endif", ""]
        (ROOT / f"src/gen/strings_{code}.h").write_text("\n".join(out), encoding="utf-8")
        sizes[code] = pos + 2 * len(keys)
    if errors:
        for e in errors:
            print("ERROR", e, file=sys.stderr)
        return 1
    print("strings: " + ", ".join(f"{c}={n} bytes" for c, n in sizes.items())
          + f" ({len(keys)} keys)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
