"""Shared identifier registry for Galleria 2007 tools.

Every enumeration that appears both in authoring data (map JSON, sprite and
texture generators, language files) and in the C cartridge is declared here
once. ``tools/build_ids.py`` turns these lists into ``src/gen/ids.h`` so the
C code and the Python tools can never disagree about a numeric value.

Order matters: the position in each list is the numeric id. Append new
entries at the end of a list to keep existing generated data stable.
"""

# Wall/flat texture ids: (name, pattern, material). Patterns are 32x32
# 4-bit luminance images; materials are 16-step colour ramps.
TEXTURES = [
    ("TUF_A", "ROUGH", "TUF"),
    ("TUF_B", "ROUGH", "TUF_DARK"),
    ("TUF_DARK", "ROUGH", "SHADOW"),
    ("TUF_CUT", "BLOCKS", "TUF"),
    ("WHITEWASH_A", "PLASTER", "WHITE"),
    ("WHITEWASH_B", "BLOCKS", "WHITE"),
    ("MASONRY_A", "MASONRY", "STONE"),
    ("MASONRY_2007_WALL", "MASONRY", "BRICK"),
    ("FLOOR_RUBBLE", "RUBBLE", "STONE"),
    ("FLOOR_STONE", "SLABS", "STONE"),
    ("CEILING_TUF", "ROUGH", "TUF_DARK"),
    ("WATER_DARK", "WATER", "WATER"),
    ("METAL_RUST", "METAL", "RUST"),
]

# Map-JSON aliases accepted for texture names (short forms used by the map).
TEXTURE_ALIASES = {"MASONRY_2007": "MASONRY_2007_WALL"}

PATTERNS = ["ROUGH", "BLOCKS", "PLASTER", "MASONRY", "RUBBLE", "SLABS",
            "WATER", "METAL"]

# Material colour anchors (sRGB). Ramps are generated from these.
MATERIALS = [
    ("TUF", (214, 170, 92)),       # yellow Neapolitan tuff
    ("TUF_DARK", (150, 110, 64)),  # shadowed / damp tuff
    ("SHADOW", (96, 74, 52)),      # deep recesses
    ("WHITE", (232, 230, 224)),    # wartime whitewash (near-neutral lime)
    ("STONE", (158, 154, 148)),    # grey paving / rubble
    ("BRICK", (178, 104, 70)),     # later masonry closure
    ("WATER", (60, 132, 150)),     # cistern water
    ("RUST", (176, 96, 48)),       # rusted iron
]

ITEMS = ["NONE", "NOTEBOOK", "CAMERA", "ROPE", "BATTERY", "KEY_A", "KEY_B",
         "TOOL", "MAP"]
# Puzzle-critical item types can never be destroyed or lost.
CRITICAL_ITEMS = {"ROPE", "KEY_A", "KEY_B", "TOOL"}

ENTITY_KINDS = ["SPAWN", "ITEM", "HIST", "CISTERN", "DOOR", "DECOR", "CLUE",
                "FICTION", "LAMPMAN", "WAYPOINT", "SIGHTING"]

DOORS = ["NONE", "GATE_A", "WALL_2007", "GRATE"]

ZONES = ["ACCESS", "TUNNEL", "CISTERN", "VEHICLES", "SHELTER", "PASSAGE",
         "CAVITY", "STAIRS"]

SECTOR_FLAGS = ["CHECKPOINT", "END", "NO_AI", "NO_PLAYER_SPAWN"]

ARCHIVE = ["GALLERIA", "CISTERNS", "SHELTERS", "DEPOSIT", "DISCOVERY",
           "STEPS", "FICTION"]

PROVENANCE = ["HIST", "PUBLIC", "RECON", "GAME", "FICTION"]

# Billboard sprites (generated by tools/build_sprites.py). Item sprites use
# the ITEM_<name> form so the renderer can map an item type to its sprite.
SPRITES = ["LAMPMAN", "PLAYER", "CAR_A", "CAR_B", "MOTO", "MARK",
           "ITEM_NOTEBOOK", "ITEM_CAMERA", "ITEM_ROPE", "ITEM_BATTERY",
           "ITEM_KEY", "ITEM_TOOL", "ITEM_MAP"]


def index(names, name, what):
    """Return the numeric id of ``name`` or abort with a helpful message."""
    keys = [n[0] if isinstance(n, tuple) else n for n in names]
    if name not in keys:
        raise SystemExit(f"unknown {what} {name!r}; expected one of {keys}")
    return keys.index(name)
